config-version: 2

name: "sample_dbt_project"

profile: "sample_dbt_project"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"

seeds:
  sample_dbt_project:
    +schema: raw
    jaffle-data:
      +enabled: "{{ var('load_source_data', false) }}"

models:
  sample_dbt_project:
    staging:
      +materialized: view
    marts:
      +materialized: table
